# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  cx-artifactory:
    type: terraform-registry
    url: https://cxaf.jfrog.io/
    token: ${{secrets.ARTIFACTORY_TF_TOKEN}}
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    registries:
      - cx-artifactory
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/terratest"
    schedule:
      interval: "weekly"
