changelog:
  exclude:
    labels:
      - ignore-for-release
      - invalid
      - duplicate
      - help wanted
      - invalid
      - question
      - wontfix
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking
    - title: Downtime 💥
      labels:
        - downtime
    - title: Migration
      labels:
        - migration
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Documentation 📖
      labels:
        - documentation
    - title: Bug Fix 🐛
      labels:
        - bug
    # Dependabot automatically labels updates with "dependencies"
    - title: Dependencies 📦
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
